server:
  port: 9191

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:

        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/**




  discovery:
    enabled: false